### ISSUE TITLE
IForum GetById should return Forum

### ISSUE THREAD

**Issue by wesdoyle** [JayMackay/Red-Lotus-Forums#4]
https://github.com/JayMackay/Red-Lotus-Forums/blob/698e7af687bcecaeeba744b945c73899ce6e7f81/LotusForums.data/IForum.cs#L9

I think this should perhaps return `Forum` type (`LotusForums.Data.Models`) rather than `IForum`

Then delete the method:

https://github.com/JayMackay/Red-Lotus-Forums/blob/183d28f4f3d8623f940ad3801acf7412f12de414/LotusForums.Service/ForumService.cs#L61-L64

**Comment by JayMackay** [comment]
Thanks, @wesdoyle that managed to resolve the issue!
